"use client";

import { useState } from 'react';
import RecipeGenerator from '../components/RecipeGenerator';
import Header from '../components/Header';
import Footer from '../components/Footer';
import Link from 'next/link';

const Home = () => {
  const [currentPage, setCurrentPage] = useState(1);

  const paragraphs = [
    "AI Recipe Generator helps you create amazing recipes with the ingredients you have at hand.",
    "Our advanced AI models ensure that you get the most delicious and creative recipes.",
    "Save time and reduce food waste by using our AI to find the best recipes for your ingredients."
  ];

  const handlePageChange = (page: number) => {
    setCurrentPage(page);
  };

  return (
    <div className="flex flex-col min-h-screen">
      <Header />
      <main className="flex-grow">
        <section className="bg-gray-100 py-12 text-center">
          <h1 className="text-5xl font-bold mb-4">Welcome to AI Recipe Generator</h1>
          <p className="text-lg text-gray-700">Your ultimate tool to create delicious recipes with the ingredients you have.</p>
          <div className="mt-8">
            <Link href="/signup" className="bg-blue-500 text-white px-4 py-2 rounded">
              Sign Up
            </Link>
            <Link href="/login" className="bg-green-500 text-white px-4 py-2 rounded ml-4">
              Login
            </Link>
          </div>
        </section>
        <section className="py-12">
          <div className="container mx-auto text-center">
            <h2 className="text-3xl font-bold mb-6">How It Works</h2>
            <div className="flex flex-col md:flex-row md:justify-around">
              <div className="md:w-1/3 p-4">
                <h3 className="text-xl font-bold">Step 1</h3>
                <p className="text-gray-700">Enter the meal you want to prepare and the ingredients you have.</p>
              </div>
              <div className="md:w-1/3 p-4">
                <h3 className="text-xl font-bold">Step 2</h3>
                <p className="text-gray-700">Specify the number of recipes you want.</p>
              </div>
              <div className="md:w-1/3 p-4">
                <h3 className="text-xl font-bold">Step 3</h3>
                <p className="text-gray-700">Get amazing recipes generated by our AI.</p>
              </div>
            </div>
          </div>
        </section>
        <section className="py-12 bg-gray-100">
          <div className="container mx-auto">
            <RecipeGenerator />
          </div>
        </section>
        <section className="py-12 bg-gray-100">
          <div className="container mx-auto text-center">
            <h2 className="text-3xl font-bold mb-6">Why Use Our AI Recipe Generator</h2>
            <div className="max-w-2xl mx-auto">
              <p className="text-gray-700">{paragraphs[currentPage - 1]}</p>
              <div className="flex justify-center mt-4">
                {paragraphs.map((_, index) => (
                  <button
                    key={index}
                    onClick={() => handlePageChange(index + 1)}
                    className={`mx-2 p-2 rounded-full ${currentPage === index + 1 ? 'bg-blue-500' : 'bg-gray-300'}`}
                  >
                    {index + 1}
                  </button>
                ))}
              </div>
            </div>
          </div>
        </section>
        <section className="py-12">
          <div className="container mx-auto text-center">
            <h2 className="text-3xl font-bold mb-6">Best Recipe Ideas</h2>
            <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
              <div className="p-4 bg-white shadow-md rounded">
                <h3 className="text-xl font-bold mb-2">Recipe Idea 1</h3>
                <p className="text-gray-700">A delicious beef stew made with your favorite ingredients.</p>
              </div>
              <div className="p-4 bg-white shadow-md rounded">
                <h3 className="text-xl font-bold mb-2">Recipe Idea 2</h3>
                <p className="text-gray-700">A tasty vegetable stir-fry that's quick and easy to make.</p>
              </div>
              <div className="p-4 bg-white shadow-md rounded">
                <h3 className="text-xl font-bold mb-2">Recipe Idea 3</h3>
                <p className="text-gray-700">A hearty soup perfect for a cozy evening.</p>
              </div>
            </div>
          </div>
        </section>
      </main>
      <Footer />
    </div>
  );
};

export default Home;
